apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: gcr.io/kubecon-china-2019/image-rec
    jibMaven: {}
deploy:
  kubectl:
    manifests:
      - k8s/web-dev.yaml

# optional profile to run the jib build on Google Cloud Build
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
